name: Lint JavaScript

on:
  pull_request:
  push:
    branches:
      - main
      - stable*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    name: eslint

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint
