name: PHP Security analysis

on:
  pull_request:
  push:
    branches:
      - main
      - stable*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Security analysis
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions:4.9.3
        with:
          security_analysis: true
          composer_ignore_platform_reqs: false
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
